### ISSUE TITLE
OperatorHub.io should support the nested bundle format

### ISSUE THREAD

**Issue by dmesser** [operator-framework/operatorhub.io#106]
OperatorHub.io currently expects a flat directory structure of an Operator bundle that holds all CRDs, CSVs and the package.yaml.
Since the rest of the Operator Framework moves to the [nested bundle format](https://github.com/operator-framework/operator-registry#manifest-format), so should OperatorHub.io

**Comment by jozzi** [comment]
Nested bundle format is now supported with PR https://github.com/operator-framework/operatorhub.io/pull/200.
Therefore we can close the issue.
