### ISSUE TITLE
CSV Bundle Editor needs to support CRD versioning

### ISSUE THREAD

**Issue by dmesser** [operator-framework/operatorhub.io#197]
Uploading CRDs with `spec.versions` instead of `spec.version` leads to CRD forms being pre-populated without the API version, example here: https://github.com/jetstack/cert-manager/blob/b8bd8dc665dae418a7c514cc414befac272cdb15/deploy/manifests/00-crds.yaml#L1364

IMHO the UI should be populated using the last entity in that list.

**Comment by tlwu2013** [comment]
Thanks for reporting this! We've captured this will be to address this in the future release, thanks!

**Comment by jozzi** [comment]
Thanks for the issue,
Bundle editor now supports the versions list together with version string.

**Comment by flickerfly** [comment]
@jozzi Thanks, works great in my testing!

Always a good start to the week when you come in on Monday and find that the problem you were going to work on was solved over the weekend.
