### ISSUE TITLE
Deprecate Dockerfile?

### ISSUE THREAD

**Issue by flickerfly** [operator-framework/operatorhub.io#210]
I tried to run the Dockerfile and ran into errors. This made me wonder if it had been moved to an S2I build method. I was successful running this S2I build in my OpenShift cluster. Perhaps this is a bit of documentation in the readme and removing the Dockerfile? If that is an approved direction, I'll submit it. 

`oc new-app registry.access.redhat.com/ubi8/nodejs-10:latest~https://github.com/operator-framework/operatorhub.io.git`

**Comment by dmesser** [comment]
The `Dockerfile` should work. S2I also works but does not fetch the Operators - you'd end up with an empty version. What errors did you see?

**Comment by flickerfly** [comment]
Sorry for the false alarm. I tried the build again and it did work this time. I should have saved what I saw Friday. Maybe I was missing some dependency at the time.
