### ISSUE TITLE
Upload of bundle does not recognize owned CRD

### ISSUE THREAD

**Issue by dmesser** [operator-framework/operatorhub.io#223]
Uploading the attached files leads to owned CRDs not being recognized by the editor even though they are correctly placed and formatted.

[minio-operator.zip](https://github.com/operator-framework/operatorhub.io/files/3772140/minio-operator.zip)

**Comment by jozzi** [comment]
@dmesser Issue is fixed in dev now
see https://github.com/operator-framework/operatorhub.io/pull/224
