### ISSUE TITLE
Embed player for asciinema.org links in operator description

### ISSUE THREAD

**Issue by guymguym** [operator-framework/operatorhub.io#229]
I think terminal recording is a great way to show a tutorial and asciinema.org is really cool.

Try one that I've made - https://asciinema.org/a/kCziF0feQD9qmNioLUSAZNoEm?speed=2&autoplay=1

See how you can pause and copy-paste the text from the player directly because it actually renders these as html.

Here is asciinema player embedding options here - https://asciinema.org/docs/embedding

Do you think it makes sense to add it so operators could use it?
I wish github would also support it in their Markdown...

**Comment by tlwu2013** [comment]
Hi @guymguym , thanks for the cool suggestions!

Currently, the markdown view in OperatorHub.io (and OpenShift Console) doesn't permit the script tags, and it doesn't render the image for screenshot linking yet.

We will evaluate if we could support rendering the image so folks can embed the image link.
But the good news is that you can alternatively at least embed the tutorial as a text link as a part of the Operator Description markdown block, so your users can open another browser tab to get the full features (i.e. pause and copy-paste the text from the player) in a separated browser tab.
