### ISSUE TITLE
IPV6 support for the operatorhub.io site

### ISSUE THREAD

**Issue by cdoan1** [operator-framework/operatorhub.io#257]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is. Example: "I have an issue when (...)"

I have an issue when I try to access the community operators in my OpenShift deployment when my OpenShift is deployed with IPV6 support. The operators list is empty because `operatorhub.io` does not have an AAAA for IPV6 network traffic.

Can we enable IPV6 support for this site.

```
➜  auth git:(master) ✗ host -t AAAA operatorhub.io
operatorhub.io has no AAAA record
```

**Comment by dmesser** [comment]
This catalog is not meant to be used with OpenShift as there are likely incompatible, non-tested Operators referenced. Use the community catalog within OpenShift instead. It contains the subset of Operator that have been tested / submitted for OpenShift.
