### ISSUE TITLE
OperatorHub.io displays a blank page

### ISSUE THREAD

**Issue by intolerance** [operator-framework/operatorhub.io#263]
**Describe the bug**
OperatorHub.io displays a blank page

**What did you do?**
1. Go to https://operatorhub.io in a modern web browser (Chrome, Firefox, Safari)

**What did you expect to see?**
The main page of OperatorHub.io 
No other pages work either.

**What did you see instead?**
A blank webpage

**Additional context**
It appears that the `https://operatorhub.io/static/app~748942c6.e6a354.bundle.js` contains HTML and not JavaScript code. This was validated by viewing the source of the `https://operatorhub.io/static/app~748942c6.e6a354.bundle.js` and the fact Chrome interprets it as type of `text/html`.

Strangly, if you navigate to https://operatorhub.io/static/app~748942c6.e6a354.bundle.js the webpage is no longer blank and functions appropriately. However, a different `bundle.js` is called out if you view the source there.
![Screen Shot 2020-03-04 at 13 46 19](https://user-images.githubusercontent.com/26014533/75916838-a6e0c680-5e1e-11ea-9a64-65c2623c0d30.png)
![Screen Shot 2020-03-04 at 13 45 49](https://user-images.githubusercontent.com/26014533/75916855-ad6f3e00-5e1e-11ea-9daa-e0c0b03db9e3.png)
![Screen Shot 2020-03-04 at 13 44 40](https://user-images.githubusercontent.com/26014533/75916870-b6600f80-5e1e-11ea-9f67-1f65b8472d3e.png)
![Screen Shot 2020-03-04 at 13 44 21](https://user-images.githubusercontent.com/26014533/75916886-bcee8700-5e1e-11ea-9fd6-36accb902c39.png)

**Comment by intolerance** [comment]
I am not really sure how the above occurred, however it has somehow managed to fix itself. 

Reviewing the source the index source prior it was calling out the script `app~{....}e6a354.bundle.js` -- however now the index source reflects `app~{...}.700b27.bundle.js` and works fine.

Before:
![Screen Shot 2020-03-04 at 14 07 24](https://user-images.githubusercontent.com/26014533/75918608-ab5aae80-5e21-11ea-9b6f-cbbb362d7b41.png)

After:
![Screen Shot 2020-03-04 at 14 08 05](https://user-images.githubusercontent.com/26014533/75918621-b4e41680-5e21-11ea-909d-a1a818d0cf9e.png)

**Comment by jozzi** [comment]
Hi Allen,
such an issue occurs if one has opened website in the tab for longer time and returns back to the app and starts to navigate in it while there happened release in the meantime.

Simple reload should solve the issue.

Was that your case @intolerance ?

**Comment by LaloLoop** [comment]
Hello, sorry to write on an old and closed issue, but this is happening again with many browsers, tested:

- Firefox desktop and mobile
- Safari desktop and mobile
- Brave mobile

I could reproduce the error, and a applied a workaround by using a VPN.

Setting my VPN to a US location allowed me to view the site, while if I tried to access it from my current location (Mexico) it failed with the blank page. 

I did not do any thorough investigation on sources being downloaded but the browser showed all requests as ok.

Please let me know if you’d need more information.

Thanks!
