### ISSUE TITLE
Expose the licences information for the operator on the landing page

### ISSUE THREAD

**Issue by dmueller2001** [operator-framework/operatorhub.io#298]
it would be nice to search on software license aka for GPL/APL vs private/proprietary license operators. 

currently you must click at least 3 times to find out what the license is 
example: https://operatorhub.io/operator/elastic-cloud-eck > https://github.com/elastic/cloud-on-k8s > https://github.com/elastic/cloud-on-k8s/blob/master/LICENSE.txt

if License was a metadata tag, it could be exposed here on the operator's landing page along with other pertainent information: 
<img width="234" alt="Screen Shot 2020-05-06 at 12 52 53 PM" src="https://user-images.githubusercontent.com/4029488/81222042-85c06180-8f98-11ea-8749-06fe84dd9eff.png">

requested by @gregswift @logdna

**Comment by dmesser** [comment]
Is the goal here to find operators that are "free" to use vs. requiring to buy a paid subscription / license? If so, we are working on annotations that would allow to specify that. They are only expected by graphical frontends running on clusters (e.g. OpenShift Console) but we could easily extend this to be reflected as optional metadata for an Operator in general.

If the ask is to provide labels on how the Operator source code is licensed, then I think this is something that every project denotes in their repository (for which we have have a field).
