### ISSUE TITLE
Create Catalog Data with the Operator SDK command removed from operator-sdk

### ISSUE THREAD

**Issue by Havilland** [operator-framework/operatorhub.io#302]
**Describe the bug**
The command 'operator-sdk olm-catalog gen-csv' in the section Create Catalog Data with the Operator SDK has been removed from the operator-sdk in version [0.15.0](https://github.com/operator-framework/operator-sdk/releases/tag/v0.15.0). Yet the Page on Operatorhub.io still references the command.

**Comment by tlwu2013** [comment]
This will be addressed in PR #325   Thanks for reaching out!

**Comment by tlwu2013** [comment]
PR https://github.com/operator-framework/operatorhub.io/pull/325 has been merged. Closed this issue. Thanks!
