### ISSUE TITLE
Bundle editor upload drag and drop does not work with Firefox

### ISSUE THREAD

**Issue by ctron** [operator-framework/operatorhub.io#308]
**Describe the bug**

Dragging and dropping a directory on the new bundle editor has no effect when using Firefox.

**What did you do?**
A clear and concise description of the steps you took. For example, steps to reproduce the behavior:
1. Go to https://operatorhub.io/packages#
2. Drag and drop valid directory (works in chrome)
3. See error

**What did you expect to see?**

The upload working.

**What did you see instead?**

No message, no response, no effect.

**Additional context**

Firefox version: 78.0.1 (64-bit)

**Comment by tlwu2013** [comment]
Hi @ctron , 

Thanks for reaching out firstly.

We've tried to reproduce the issue on our end with Firefox version 78.0.2 (64-bit) but cannot reproduce the issue:
![drag-n-drop_firefox_78 0 2](https://user-images.githubusercontent.com/5903705/88237819-f04a7a80-cc34-11ea-907f-8cb0777307e0.gif)

Can you help point out if we missed something or if Firefox version 78.0.2 (64-bit) also works on your end?

Thanks!

**Comment by ctron** [comment]
Of course I could post now a video of it not working, but maybe the console log helps as well:

~~~
This page uses the non standard property “zoom”. Consider using calc() in the relevant property values, or using “transform” along with “transform-origin: 0 0”. packages
Some cookies are misusing the recommended “sameSite“ attribute 14
Uncaught TypeError: a[0] is undefined
    t PackageUploaderDropArea.tsx:183
    React 12
    unstable_runWithPriority scheduler.production.min.js:18
    React 2
PackageUploaderDropArea.tsx:183:22
    t PackageUploaderDropArea.tsx:183
    React 12
    unstable_runWithPriority scheduler.production.min.js:18
    React 2
    kn self-hosted:897

~~~
