### ISSUE TITLE
OperatorHub "submitting your operator " link is broken

### ISSUE THREAD

**Issue by n1r1** [operator-framework/operatorhub.io#340]
There's a link in [this page](https://operatorhub.io/contribute) named "submitting your operator " which points to a non existent resource:
https://github.com/operator-framework/community-operators/blob/master/docs/contributing.md#submitting-your-operator

so users get 404 instead of instructions on how to submit an operator.

Possibly this needs to be changed but no idea what should be the new link:
https://github.com/operator-framework/operatorhub.io/blob/master/frontend/src/utils/documentationLinks.ts#L4

**Comment by dmesser** [comment]
You are right, we missed this when we restructured the docs. Fix is underway, stay tuned. For now look here https://operator-framework.github.io/community-operators/packaging-operator/ (will be moved into a better location soon)
